### ISSUE TITLE
StreamGalleryPicker initialLoad not called

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1431]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

Android

### What version are you using?

  stream_chat_flutter: 5.2.0
  stream_chat_localizations: 4.0.0
  stream_chat_persistence: 5.1.0

### What happened?

When clicking the attachments the stream_gallery_picker creates a StreamPhotoGalleryController, which is passed to the actual stream_photo_gallery widget, which shows the gallery photos in the first tab of the attachments bottom sheet. 

Currently this list remains empty as the controllers `doInitialLoad` is never called.
In addition the empty message is wrong as it uses `context.translations.noUsersLabel` instead of something related to the gallery.

### Steps to reproduce

```bash
1. Use default StreamMessageInput
2. Click attachments button
3. allow all permissions
4. see empty list with wrong error message instead of actual gallery
```

### Flutter analyze output

```shell
No issues found! (ran in 84.9s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/floriandaniel/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/floriandaniel/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/floriandaniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
Hey @flodaniel,
could you let us know on which device/Android version do you found that problem?

**Comment by flodaniel** [comment]
A Pixel 7 Pro with Android 13

**Comment by adasiewiczr** [comment]
hey @flodaniel,
the issue was fixed in the PRs mentioned above. We also released a new version `5.3.0` that contains a fix.

**Comment by flodaniel** [comment]
I just tested this with 5.3.0 and #1439 did not fix this issue @adasiewiczr.

**Comment by adasiewiczr** [comment]
hey @flodaniel,
did you add additional permissions to the AndroidManfiest as mentioned [here](https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_flutter#android)?

**Comment by flodaniel** [comment]
initiall i did not. 
I now did and I also made sure to use the gradle versions specified here: https://pub.dev/packages/photo_manager#kotlin-gradle-agp. 

Even after a `flutter clean`, the preview is not populated with images.

**Comment by flodaniel** [comment]
Hey @adasiewiczr,

can you reopen this issue, or are you unable to reproduce it? The two linked PRs #1439 and #1441 do not tackle any loading issues.

**Comment by adasiewiczr** [comment]
hey @flodaniel,
we were testing the issue using our [sample app](https://github.com/GetStream/stream-chat-flutter/tree/develop/packages/stream_chat_flutter/example) and we couldn't reproduce it after the fixes.
Could you check how it works for you? If everything works fine in our sample, it would be helpful if you could provide an MVP project that reproduces the behavior.

**Comment by flodaniel** [comment]
I can confirm that this also works on the sample app for my device. I will have to re-check our setup! Thanks for your help :)

**Comment by adasiewiczr** [comment]
🙌 thank you for letting us know!
