### ISSUE TITLE
disabling attachments on MessageInput throws errors

### ISSUE THREAD

**Issue by parikh20** [GetStream/stream-chat-flutter#426]
**Describe the bug**
disabling attachments on MessageInput throws errors

**What package are you using? What version?**
stream_chat_flutter 2.0.0-nullsafety.2

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1) Use the provided examples here https://getstream.io/chat/flutter/tutorial/#add-stream-chat-to-your-flutter-application
2) In the ChannelPage class, in the MessageInput widget, set disableAttachments to true
3) Hot reload and errors will occur about width

**Expected behavior**
For the attachment button to go away and no errors

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14895674/117603219-64440980-b107-11eb-93aa-0dc007e8bda6.PNG)

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.
No errors

Paste the output of running `flutter doctor -v` here.
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\jaine\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\jaine\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Samsung Galaxy S10 (mobile) • 192.168.105.102:5555 • android-x86    • Android 10 (API 29)
    • Edge (web)                  • edge                 • web-javascript • Microsoft Edge 90.0.818.56

**Comment by imtoori** [comment]
@parikh20 this should be fixed in version `stream_chat_flutter 2.0.0-nullsafety.3`
can you check please?

**Comment by imtoori** [comment]
@parikh20 I'm trying reproducing the bug, but it's working fine for me 
how are you using the MessageInput?

**Comment by parikh20** [comment]
I'm using your stream_chat_v1 sample to test around and it still occurs in that version. Adding disableAttachments to a MessageInput causes a rendering error and results in a white screen. I tried this with the new chat screen. Please try again.

**Comment by parikh20** [comment]
I'm using it as such:

`Scaffold(
      appBar: ChannelHeader(),
      body: SafeArea(
        child: Column(
          children: <Widget>[
            Expanded(
              child: MessageListView(),
            Padding(
              padding: EdgeInsets.only(bottom: 5.0),
              child: MessageInput(
              ),
            ),
          ],
        ),
      ),
    );`

Tried it with a fresh flutter app and the bug does seem to be resolved in there. Seems to be some bug in my widget tree which is strange since it is mostly unmodified from your guys' tutorials. I'll get around to investigating this bug sometime in the future.

**Comment by imtoori** [comment]
I've tried running that snippet and it's working fine
I thought it was because of the Padding or SafeArea but it actually works fine 
I'll close this issue for the moment, feel free to reopen it when you have more details
