### ISSUE TITLE
The search does not find a new message

### ISSUE THREAD

**Issue by NiyazFazlyev** [GetStream/stream-chat-flutter#887]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: 3.3.2

### What happened?

I am implementing a message search by chats, everything works fine, except when the search occurs on a message that has just been sent. 

Here is the part of the code I use

> MessageSearchListView(
                  showErrorTile: true,
                  showResultCount: false,
                  messageQuery: messageQuery,
                  filters: Filter.in_('members', [StreamChat.of(context).currentUser?.id ?? '']),
                  sortOptions: const [
                    SortOption('created_at', direction: SortOption.ASC),
                  ],
                  pullToRefresh: false,
                  itemBuilder: (context, response) => itemBuilder(context, response, messageQuery),
                  separatorBuilder: (context, index) => const Divider(color: Colors.white, thickness: 1, height: 1),

Message not found     
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-02-04 at 00 08 23](https://user-images.githubusercontent.com/51171687/152433556-de53c0a7-b86f-4512-9ff4-3567ce74eaef.png)

After a while, the message was found
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-02-04 at 00 27 57](https://user-images.githubusercontent.com/51171687/152433574-544e8040-76fc-4d45-a41c-50aaac93d199.png)
             loadingBuilder: (ctx) => const ChannelLoadingPage(),
),

### Steps to reproduce

```bash
1. Send a message in a chat
2. Go to Message search and search for the message you just sent
3. Wait about 10 minutes and repeat the same request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @NiyazFazlyev 
This is not related to the Flutter SDK
The backend team is working on improving the real-time indexing and will release something really soon
Feel free to contact support if you need more information

**Comment by developerpaaji** [comment]
Any updates on this issue

**Comment by imtoori** [comment]
this should be solved as far as I know @developerpaaji

**Comment by developerpaaji** [comment]
@imtoori this issue still exists I am testing it on **desk_web_dev** branch

**Comment by imtoori** [comment]
@developerpaaji can you email support? I think we'll your app id, this is most probably related to backend and not to the flutter sdk
